### PR TITLE
Added settings file, new mode, fixed undefined index

### PR DESCRIPTION
**Pull request by drwonky**
Added redirect mode for embedding as an img src in a page
Moved settings into an included file so code/settings are separate
Fixed "Undefined index: cat_id" warning

### CODE REVIEW

**Comment by moy** [comment]
Hi,

Sorry, apparently this went under the radar :-(, and thanks for your contribution.

Ideally, the different changes should be each in its own commit, but I can live with one big commit.

Can you rebase your changes on top of current master?

What's the advantage of the redirect mode? This should be documented in the README.md file so that other users can benefit from it.

**Comment by moy** [comment]
Hi,

Just a ping: I can take care of rebasing, but currently I don't understand the advantage of redirect mode (I guess there is one, but I don't get it). Can you give me a hint?

Thanks,

**Comment by drwonky** [comment]
Redirect mode generates a 302 redirect so you can reference the script as the target of a URL or the src of an  tag.  This allows you to embed random images in a web page.

When a visitor comes to my site they get a random image selection for that portion of the page.  You could use it for random backgrounds, etc.

**Comment by moy** [comment]
Ah, nice, so you can integrate in any static page, without even relying on JavaScript. Will merge.

**Comment by moy** [comment]
I've split and rebased your patch, and added documentation and examples in the master branch. I'm closing this one. Feedback welcome on the content of master.

**Pull request closed without merging**
